name: Build and Commit Published Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the token can push changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET backend
      run: dotnet publish PortfolioAPI/PortfolioAPI.csproj -c Release -o published-files/backend

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: portfolio-frontend

    - name: Build Angular app
      run: npm run build
      working-directory: portfolio-frontend

    - name: Copy Angular dist to published folder
      run: |
        mkdir -p published-files/frontend
        cp -r portfolio-frontend/dist/* published-files/frontend/

    - name: Set up Git credentials
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Commit and push published files
      run: |
        git add published-files/
        git commit -m "chore: update published build files" || echo "No changes to commit"
        git push origin main
