name: Build and Commit Published Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout your code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Restore and publish .NET
    - name: Publish .NET backend
      run: dotnet publish PortfolioAPI/PortfolioAPI.csproj -c Release -o published-files/backend

    # Set up Node.js for Angular
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install and build Angular
    - name: Install dependencies
      run: npm ci
      working-directory: portfolio-frontend

    - name: Build Angular app
      run: npm run build
      working-directory: portfolio-frontend

    - name: Copy Angular dist to published folder
      run: |
        mkdir -p published-files/frontend
        cp -r portfolio-frontend/dist/* published-files/frontend/

    # Commit published files
    - name: Commit and push published files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add published-files/
        git commit -m "chore: update published build files" || echo "No changes to commit"
        git push origin main
